<?php
/*************************************************************************************************************************
**************************************************************************************************************************
**************************************************************************************************************************

WARNING!!!

THIS FILE SHOULD NOT BE EDITED - IT WILL BE AUTOGENERATED EACH TIME THE MODELS ARE BUILT!

OVERRIDE SETTINGS IN MODEL NOT THE BASEMODEL

**************************************************************************************************************************
**************************************************************************************************************************
*************************************************************************************************************************/

namespace project\db\om\adm201\base;

/**
 * BaseSamplesetTable class 
 * 
 * BaseSamplesetTable
 * 
 * @author Christopher Beck <cwbeck@gmail.com>
 * @version SVN: $id
 * @package adm201
 * @subpackage base
 */
class BaseSamplesetTable extends \nano\core\db\om\BaseTable {

	protected $modelName = 'Sampleset';
	protected $primaryKey = array('id');
	protected $dbConfig = 'default';
	protected $dbName = 'adm201';
	protected $tableName = 'Samplesets';
	protected $fields = array(
		'id' => array(
			'mysql_type' => 'int(11) unsigned',
			'mysql_is_null' => 'NO',
			'mysql_key' => 'PRI',
			'mysql_default' => '',
			'mysql_extra' => 'auto_increment',
			'is_foreign_reference' => false,
			'use_model' => 'Sampleset',
			'use_database' => 'adm201',
			'set_function' => 'setId',
			'validation_function' => 'validateId',
			'get_function' => 'getId',
		),
		'notes' => array(
			'mysql_type' => 'mediumtext',
			'mysql_is_null' => 'YES',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Sampleset',
			'use_database' => 'adm201',
			'set_function' => 'setNotes',
			'validation_function' => 'validateNotes',
			'get_function' => 'getNotes',
		),
		'url' => array(
			'mysql_type' => 'mediumtext',
			'mysql_is_null' => 'YES',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Sampleset',
			'use_database' => 'adm201',
			'set_function' => 'setUrl',
			'validation_function' => 'validateUrl',
			'get_function' => 'getUrl',
		),
		'date_collected' => array(
			'mysql_type' => 'datetime',
			'mysql_is_null' => 'YES',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Sampleset',
			'use_database' => 'adm201',
			'set_function' => 'setDateCollected',
			'validation_function' => 'validateDateCollected',
			'get_function' => 'getDateCollected',
		)
	);
	protected $newFieldNameMap = array(
		'id' => 'id',
		'notes' => 'notes',
		'url' => 'url',
		'date_collected' => 'date_collected'
	);

	public function retrieveByPk($id) {
		$query = new \nano\core\db\core\SelectQuery();
		$query->from('Samplesets')->where('`Samplesets`.`id` = "'.addslashes($id).'" LIMIT 1');
		$results = $this->doSelect($query);
		return isset($results[0]['Sampleset'])? $results[0]['Sampleset'] : null;
	}

}