<?php
/*************************************************************************************************************************
**************************************************************************************************************************
**************************************************************************************************************************

WARNING!!!

THIS FILE SHOULD NOT BE EDITED - IT WILL BE AUTOGENERATED EACH TIME THE MODELS ARE BUILT!

OVERRIDE SETTINGS IN MODEL NOT THE BASEMODEL

**************************************************************************************************************************
**************************************************************************************************************************
*************************************************************************************************************************/

namespace project\db\om\adm201\base;

/**
 * BaseAnswerTable class 
 * 
 * BaseAnswerTable
 * 
 * @author Christopher Beck <cwbeck@gmail.com>
 * @version SVN: $id
 * @package adm201
 * @subpackage base
 */
class BaseAnswerTable extends \nano\core\db\om\BaseTable {

	protected $modelName = 'Answer';
	protected $primaryKey = array('id');
	protected $dbConfig = 'default';
	protected $dbName = 'adm201';
	protected $tableName = 'Answers';
	protected $fields = array(
		'id' => array(
			'mysql_type' => 'int(11) unsigned',
			'mysql_is_null' => 'NO',
			'mysql_key' => 'PRI',
			'mysql_default' => '',
			'mysql_extra' => 'auto_increment',
			'is_foreign_reference' => false,
			'use_model' => 'Answer',
			'use_database' => 'adm201',
			'set_function' => 'setId',
			'validation_function' => 'validateId',
			'get_function' => 'getId',
		),
		'Question' => array(
			'mysql_type' => 'int(11)',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => true,
			'use_model' => 'Question',
			'use_database' => 'adm201',
			'set_function' => 'setQuestion',
			'validation_function' => 'validateQuestion',
			'get_function' => 'getQuestion',
		),
		'answer' => array(
			'mysql_type' => 'mediumtext',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Answer',
			'use_database' => 'adm201',
			'set_function' => 'setAnswer',
			'validation_function' => 'validateAnswer',
			'get_function' => 'getAnswer',
		),
		'is_correct' => array(
			'mysql_type' => 'tinyint(1)',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '0',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Answer',
			'use_database' => 'adm201',
			'set_function' => 'setIsCorrect',
			'validation_function' => 'validateIsCorrect',
			'get_function' => 'getIsCorrect',
		),
		'match_order' => array(
			'mysql_type' => 'int(11)',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '0',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Answer',
			'use_database' => 'adm201',
			'set_function' => 'setMatchOrder',
			'validation_function' => 'validateMatchOrder',
			'get_function' => 'getMatchOrder',
		),
		'alpha' => array(
			'mysql_type' => 'varchar(50)',
			'mysql_is_null' => 'YES',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Answer',
			'use_database' => 'adm201',
			'set_function' => 'setAlpha',
			'validation_function' => 'validateAlpha',
			'get_function' => 'getAlpha',
		)
	);
	protected $newFieldNameMap = array(
		'id' => 'id',
		'Question' => 'Question',
		'answer' => 'answer',
		'is_correct' => 'is_correct',
		'match_order' => 'match_order',
		'alpha' => 'alpha'
	);

	public function retrieveByPk($id) {
		$query = new \nano\core\db\core\SelectQuery();
		$query->from('Answers')->where('`Answers`.`id` = "'.addslashes($id).'" LIMIT 1');
		$results = $this->doSelect($query);
		return isset($results[0]['Answer'])? $results[0]['Answer'] : null;
	}

}