<?php
/*************************************************************************************************************************
**************************************************************************************************************************
**************************************************************************************************************************

WARNING!!!

THIS FILE SHOULD NOT BE EDITED - IT WILL BE AUTOGENERATED EACH TIME THE MODELS ARE BUILT!

OVERRIDE SETTINGS IN MODEL NOT THE BASEMODEL

**************************************************************************************************************************
**************************************************************************************************************************
*************************************************************************************************************************/

namespace project\db\om\adm201\base;

/**
 * BaseRoundTable class 
 * 
 * BaseRoundTable
 * 
 * @author Christopher Beck <cwbeck@gmail.com>
 * @version SVN: $id
 * @package adm201
 * @subpackage base
 */
class BaseRoundTable extends \nano\core\db\om\BaseTable {

	protected $modelName = 'Round';
	protected $primaryKey = array('id');
	protected $dbConfig = 'default';
	protected $dbName = 'adm201';
	protected $tableName = 'Rounds';
	protected $fields = array(
		'id' => array(
			'mysql_type' => 'int(11) unsigned',
			'mysql_is_null' => 'NO',
			'mysql_key' => 'PRI',
			'mysql_default' => '',
			'mysql_extra' => 'auto_increment',
			'is_foreign_reference' => false,
			'use_model' => 'Round',
			'use_database' => 'adm201',
			'set_function' => 'setId',
			'validation_function' => 'validateId',
			'get_function' => 'getId',
		),
		'round_start' => array(
			'mysql_type' => 'datetime',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Round',
			'use_database' => 'adm201',
			'set_function' => 'setRoundStart',
			'validation_function' => 'validateRoundStart',
			'get_function' => 'getRoundStart',
		),
		'round_end' => array(
			'mysql_type' => 'datetime',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Round',
			'use_database' => 'adm201',
			'set_function' => 'setRoundEnd',
			'validation_function' => 'validateRoundEnd',
			'get_function' => 'getRoundEnd',
		),
		'correct' => array(
			'mysql_type' => 'int(11)',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '0',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Round',
			'use_database' => 'adm201',
			'set_function' => 'setCorrect',
			'validation_function' => 'validateCorrect',
			'get_function' => 'getCorrect',
		),
		'wrong' => array(
			'mysql_type' => 'int(11)',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '0',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Round',
			'use_database' => 'adm201',
			'set_function' => 'setWrong',
			'validation_function' => 'validateWrong',
			'get_function' => 'getWrong',
		)
	);
	protected $newFieldNameMap = array(
		'id' => 'id',
		'round_start' => 'round_start',
		'round_end' => 'round_end',
		'correct' => 'correct',
		'wrong' => 'wrong'
	);

	public function retrieveByPk($id) {
		$query = new \nano\core\db\core\SelectQuery();
		$query->from('Rounds')->where('`Rounds`.`id` = "'.addslashes($id).'" LIMIT 1');
		$results = $this->doSelect($query);
		return isset($results[0]['Round'])? $results[0]['Round'] : null;
	}

}