<?php
/*************************************************************************************************************************
**************************************************************************************************************************
**************************************************************************************************************************

WARNING!!!

THIS FILE SHOULD NOT BE EDITED - IT WILL BE AUTOGENERATED EACH TIME THE MODELS ARE BUILT!

OVERRIDE SETTINGS IN MODEL NOT THE BASEMODEL

**************************************************************************************************************************
**************************************************************************************************************************
*************************************************************************************************************************/

namespace project\db\om\adm201\base;

/**
 * BaseQuestionTable class 
 * 
 * BaseQuestionTable
 * 
 * @author Christopher Beck <cwbeck@gmail.com>
 * @version SVN: $id
 * @package adm201
 * @subpackage base
 */
class BaseQuestionTable extends \nano\core\db\om\BaseTable {

	protected $modelName = 'Question';
	protected $primaryKey = array('id');
	protected $dbConfig = 'default';
	protected $dbName = 'adm201';
	protected $tableName = 'Questions';
	protected $fields = array(
		'id' => array(
			'mysql_type' => 'int(11) unsigned',
			'mysql_is_null' => 'NO',
			'mysql_key' => 'PRI',
			'mysql_default' => '',
			'mysql_extra' => 'auto_increment',
			'is_foreign_reference' => false,
			'use_model' => 'Question',
			'use_database' => 'adm201',
			'set_function' => 'setId',
			'validation_function' => 'validateId',
			'get_function' => 'getId',
		),
		'question' => array(
			'mysql_type' => 'mediumtext',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Question',
			'use_database' => 'adm201',
			'set_function' => 'setQuestion',
			'validation_function' => 'validateQuestion',
			'get_function' => 'getQuestion',
		),
		'max_answers' => array(
			'mysql_type' => 'int(11)',
			'mysql_is_null' => 'YES',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Question',
			'use_database' => 'adm201',
			'set_function' => 'setMaxAnswers',
			'validation_function' => 'validateMaxAnswers',
			'get_function' => 'getMaxAnswers',
		),
		'tip' => array(
			'mysql_type' => 'mediumtext',
			'mysql_is_null' => 'YES',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Question',
			'use_database' => 'adm201',
			'set_function' => 'setTip',
			'validation_function' => 'validateTip',
			'get_function' => 'getTip',
		),
		'match_type' => array(
			'mysql_type' => 'tinyint(1)',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '0',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Question',
			'use_database' => 'adm201',
			'set_function' => 'setMatchType',
			'validation_function' => 'validateMatchType',
			'get_function' => 'getMatchType',
		),
		'Sampleset' => array(
			'mysql_type' => 'tinyint(3)',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '3',
			'mysql_extra' => '',
			'is_foreign_reference' => true,
			'use_model' => 'Sampleset',
			'use_database' => 'adm201',
			'set_function' => 'setSampleset',
			'validation_function' => 'validateSampleset',
			'get_function' => 'getSampleset',
		)
	);
	protected $newFieldNameMap = array(
		'id' => 'id',
		'question' => 'question',
		'max_answers' => 'max_answers',
		'tip' => 'tip',
		'match_type' => 'match_type',
		'Sampleset' => 'Sampleset'
	);

	public function retrieveByPk($id) {
		$query = new \nano\core\db\core\SelectQuery();
		$query->from('Questions')->where('`Questions`.`id` = "'.addslashes($id).'" LIMIT 1');
		$results = $this->doSelect($query);
		return isset($results[0]['Question'])? $results[0]['Question'] : null;
	}

}