<?php
/*************************************************************************************************************************
**************************************************************************************************************************
**************************************************************************************************************************

WARNING!!!

THIS FILE SHOULD NOT BE EDITED - IT WILL BE AUTOGENERATED EACH TIME THE MODELS ARE BUILT!

OVERRIDE SETTINGS IN MODEL NOT THE BASEMODEL

**************************************************************************************************************************
**************************************************************************************************************************
*************************************************************************************************************************/

namespace project\db\om\adm201\base;

/**
 * BaseQuestion class 
 * 
 * BaseQuestion
 * 
 * @author Christopher Beck <cwbeck@gmail.com>
 * @version SVN: $id
 * @package adm201
 * @subpackage base
 */
class BaseQuestion extends \nano\core\db\om\Base {

	protected $modelName = 'Question';
	protected $primaryKey = array('id');
	protected $dbConfig = 'default';
	protected $dbName = 'adm201';
	protected $tableName = 'Questions';
	protected $fields = array(
		'id' => array(
			'mysql_type' => 'int(11) unsigned',
			'mysql_is_null' => 'NO',
			'mysql_key' => 'PRI',
			'mysql_default' => '',
			'mysql_extra' => 'auto_increment',
			'is_foreign_reference' => false,
			'use_model' => 'Question',
			'use_database' => 'adm201',
			'set_function' => 'setId',
			'validation_function' => 'validateId',
			'get_function' => 'getId',
		),
		'question' => array(
			'mysql_type' => 'mediumtext',
			'mysql_is_null' => 'YES',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Question',
			'use_database' => 'adm201',
			'set_function' => 'setQuestion',
			'validation_function' => 'validateQuestion',
			'get_function' => 'getQuestion',
		),
		'max_answers' => array(
			'mysql_type' => 'int(11)',
			'mysql_is_null' => 'YES',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Question',
			'use_database' => 'adm201',
			'set_function' => 'setMaxAnswers',
			'validation_function' => 'validateMaxAnswers',
			'get_function' => 'getMaxAnswers',
		),
		'tip' => array(
			'mysql_type' => 'mediumtext',
			'mysql_is_null' => 'YES',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Question',
			'use_database' => 'adm201',
			'set_function' => 'setTip',
			'validation_function' => 'validateTip',
			'get_function' => 'getTip',
		),
		'match_type' => array(
			'mysql_type' => 'bit(1)',
			'mysql_is_null' => 'YES',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Question',
			'use_database' => 'adm201',
			'set_function' => 'setMatchType',
			'validation_function' => 'validateMatchType',
			'get_function' => 'getMatchType',
		),
		'Sampleset' => array(
			'mysql_type' => 'int(11)',
			'mysql_is_null' => 'YES',
			'mysql_key' => 'MUL',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => true,
			'use_model' => 'Sampleset',
			'use_database' => 'adm201',
			'set_function' => 'setSampleset',
			'validation_function' => 'validateSampleset',
			'get_function' => 'getSampleset',
		)
	);
	protected $newFieldNameMap = array(
		'id' => 'id',
		'question' => 'question',
		'max_answers' => 'max_answers',
		'tip' => 'tip',
		'match_type' => 'match_type',
		'Sampleset' => 'Sampleset'
	);
	public function setId($value){
		if(\project\db\om\adm201\Question::validateId($value)){
			$this->id = $value;
		} else {
			throw new \nano\core\exception\ValidationException('Validation of column `id` failed');
		}
	}
	public function setQuestion($value){
		if(\project\db\om\adm201\Question::validateQuestion($value)){
			$this->question = $value;
		} else {
			throw new \nano\core\exception\ValidationException('Validation of column `question` failed');
		}
	}
	public function setMaxAnswers($value){
		if(\project\db\om\adm201\Question::validateMaxAnswers($value)){
			$this->max_answers = $value;
		} else {
			throw new \nano\core\exception\ValidationException('Validation of column `max_answers` failed');
		}
	}
	public function setTip($value){
		if(\project\db\om\adm201\Question::validateTip($value)){
			$this->tip = $value;
		} else {
			throw new \nano\core\exception\ValidationException('Validation of column `tip` failed');
		}
	}
	public function setMatchType($value){
		if(\project\db\om\adm201\Question::validateMatchType($value)){
			$this->match_type = $value;
		} else {
			throw new \nano\core\exception\ValidationException('Validation of column `match_type` failed');
		}
	}
	public function setSampleset($value){
		if(\project\db\om\adm201\Question::validateSampleset($value)){
			$this->Sampleset = $value;
		} else {
			throw new \nano\core\exception\ValidationException('Validation of column `Sampleset` failed');
		}
	}
	public function getId(){
		return $this->id;
	}
	public function getQuestion(){
		return $this->question;
	}
	public function getMaxAnswers(){
		return $this->max_answers;
	}
	public function getTip(){
		return $this->tip;
	}
	public function getMatchType(){
		return $this->match_type;
	}
	public function getSampleset(){
		return $this->Sampleset;
	}
	public static function validateId($value){
		return true;
	}
	public static function validateQuestion($value){
		return true;
	}
	public static function validateMaxAnswers($value){
		return true;
	}
	public static function validateTip($value){
		return true;
	}
	public static function validateMatchType($value){
		return true;
	}
	public static function validateSampleset($value){
		return true;
	}
	
}